import { describe, expect, it } from "vitest";
import { RandomStreams, SeededRandom, SimRandomProvider } from "@echosim/core";

/**
 * GOLDEN VECTORS generated by the original .NET implementation
 * (legacy/dotnet/tools/CrossCheck). If these ever change, the TypeScript
 * simulation has drifted from the validated semantics of EchoSim v0.1.
 */
describe("cross-implementation determinism (.NET golden vectors)", () => {
  it("SplitMix64 uint64 sequence matches .NET exactly (seed 1234)", () => {
    const rng = new SeededRandom(1234);
    expect([
      rng.nextUint64(),
      rng.nextUint64(),
      rng.nextUint64(),
      rng.nextUint64(),
      rng.nextUint64(),
    ]).toEqual([
      13478418381427711195n,
      10936887474700444964n,
      3728693401281897946n,
      5648149391703318579n,
      13335972132106093989n,
    ]);
  });

  it("nextDouble matches .NET exactly", () => {
    const rng = new SeededRandom(1234);
    for (let i = 0; i < 5; i++) rng.nextUint64(); // C# program drew 5 u64s first
    const doubles = [rng.nextDouble(), rng.nextDouble(), rng.nextDouble(), rng.nextDouble(), rng.nextDouble()];
    expect(doubles).toEqual([
      0.6904250752526857,
      0.49530330712158877,
      0.2276362924745743,
      0.3648795350527829,
      0.8019050337152652,
    ]);
  });

  it("nextInt(3,8) matches .NET exactly", () => {
    const rng = new SeededRandom(1234);
    for (let i = 0; i < 5; i++) rng.nextUint64();
    for (let i = 0; i < 5; i++) rng.nextDouble();
    const ints: number[] = [];
    for (let i = 0; i < 8; i++) ints.push(rng.nextInt(3, 8));
    expect(ints).toEqual([6, 6, 3, 7, 5, 3, 6, 6]);
  });

  it("named streams match .NET exactly", () => {
    expect(new SimRandomProvider(1234).getStream(RandomStreams.World).nextUint64())
      .toBe(16851114606058227275n);
    expect(new SimRandomProvider(1234).getStream(RandomStreams.Agents).nextUint64())
      .toBe(3342103141586333788n);
    expect(new SimRandomProvider(1234).getStream(RandomStreams.Social).nextUint64())
      .toBe(11286988656557229397n);
  });
});
